### ISSUE TITLE
Error: Skip cache put base_boroughs/7/63/42@2x (performance)

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-britain#279]
Servers is responding with `504 Gateway Time-out` error

`sudo -u nodeapp pm2 logs` shows log entries like

```
3|colourin |     at Object.put (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/tileCache.ts:44:19)
3|colourin |     at im (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/getTileWithCaching.ts:9:29)
3|colourin |     at /var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/tileserver.ts:20:15
3|colourin | Error: Skip cache put base_boroughs/7/63/42@2x
3|colourin |     at Object.put (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/tileCache.ts:44:19)
3|colourin |     at im (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/getTileWithCaching.ts:9:29)
3|colourin |     at /var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/tileserver.ts:20:15
3|colourin | Error: Skip cache put base_boroughs/8/127/84@2x
3|colourin |     at Object.put (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/tileCache.ts:44:19)
3|colourin |     at im (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/getTileWithCaching.ts:9:29)
3|colourin |     at /var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/tileserver.ts:20:15
3|colourin | Error: Skip cache put base_boroughs/8/128/85@2x
3|colourin |     at Object.put (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/tileCache.ts:44:19)
3|colourin |     at im (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/getTileWithCaching.ts:9:29)
3|colourin |     at /var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/tileserver.ts:20:15
```

`top` is showing heavy `postgres` activity which may be related to #173 (@polly64 - maybe you were using site and run into this problem?)

`@2x` indicates retina tiles which may be result of user with retina display visiting site

This should not happened - if cache is skipped then tiles should not be generated

Is it possible that it was some sort of automation, not a human user visiting site

**Comment by matkoniecz** [comment]
Ideas: 

- make more clear log (why this cache put was skipped)
- why we have `shouldUseCache` ? In which case tiles should be rendered and not cached? Especially `base_boroughs` ?
- is directly accessing tiles (rather than while using site) mattering
- is it possible to reproduce it with directly accessing such tile

**Comment by matkoniecz** [comment]
opening https://colouring.london/tiles/base_boroughs/7/63/42@2x.png reliably results in `Error: Skip cache put base_boroughs/7/63/42@2x` on server

is this tile actually generated? Note that map is zoom level limited in way that should not trigger this query. How this got triggered on live server? Is retina display requesting tiles from lower zoom levels? (AFAIK no)


https://colouring.london/tiles/base_boroughs/9/256/168.png does not result in errors (as expected)

Also, note that server slowdown may be unrelated to this errors in logs

**Comment by matkoniecz** [comment]
should be fixed by https://github.com/colouring-cities/colouring-core/pull/1326
