### ISSUE TITLE
ERROR:  column "community_building_hominess_avg" does not exist

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-britain#283]
I see in logs at production

```
3|colouringlondon  | Error: Postgis Plugin: ERROR:  column "community_building_hominess_avg" does not exist
3|colouringlondon  | LINE 9:             community_building_hominess_avg
3|colouringlondon  |                     ^
3|colouringlondon  | in executeQuery Full sql was: 'SELECT * FROM (
3|colouringlondon  |         SELECT
3|colouringlondon  |             d.*,
3|colouringlondon  |             g.geometry_geom
3|colouringlondon  |         FROM (
3|colouringlondon  |             
3|colouringlondon  |         SELECT
3|colouringlondon  |             geometry_id,
3|colouringlondon  |             community_building_hominess_avg
3|colouringlondon  |         FROM
3|colouringlondon  |             buildings
3|colouringlondon  |         WHERE
3|colouringlondon  |             community_building_hominess_avg > 0
3|colouringlondon  |     
3|colouringlondon  |         ) AS d
3|colouringlondon  |         JOIN
3|colouringlondon  |             geometries AS g
3|colouringlondon  |         ON d.geometry_id = g.geometry_id
3|colouringlondon  |         JOIN
3|colouringlondon  |             buildings AS b
3|colouringlondon  |         ON d.geometry_id = b.geometry_id
3|colouringlondon  |         WHERE
3|colouringlondon  |             b.latest_demolish_date IS NULL
3|colouringlondon  |     ) AS data
3|colouringlondon  |      LIMIT 0'
3|colouringlondon  |     at renderDataSourceTile (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/renderDataSourceTile.ts:34:21)
3|colouringlondon  |     at renderBuildingTile (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/rendererDefinition.ts:44:38)
3|colouringlondon  |     at renderTile (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/rendererDefinition.ts:54:16)
3|colouringlondon  |     at /var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/getTileWithCaching.ts:7:26
```

**Comment by matkoniecz** [comment]
#292
