### ISSUE TITLE
Error: Postgis Plugin: ERROR:  column "community_building_hominess_avg" does not exist

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-britain#292]
```
Error: Postgis Plugin: ERROR:  column "community_building_hominess_avg" does not exist
LINE 9:             community_building_hominess_avg
                    ^
in executeQuery Full sql was: 'SELECT * FROM (
        SELECT
            d.*,
            g.geometry_geom
        FROM (
            
        SELECT
            geometry_id,
            community_building_hominess_avg
        FROM
            buildings
        WHERE
            community_building_hominess_avg > 0
    
        ) AS d
        JOIN
            geometries AS g
        ON d.geometry_id = g.geometry_id
        JOIN
            buildings AS b
        ON d.geometry_id = b.geometry_id
        WHERE
            b.latest_demolish_date IS NULL
    ) AS data
     LIMIT 0'

    at renderDataSourceTile (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/renderDataSourceTile.ts:34:21)
    at renderBuildingTile (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/rendererDefinition.ts:44:38)
    at renderTile (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/rendererDefinition.ts:54:16)
    at /var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/getTileWithCaching.ts:7:26
```

**Comment by matkoniecz** [comment]
happens/happened on production

not sure when, see https://github.com/colouring-cities/colouring-core/issues/1325

**Comment by mdsimpson42** [comment]
It looks like the scripts to update the database hadn't been executed. I've done this now and tested it - the neuroaesthetic features are now working, so I'm closing this.
